// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC41Cz0vJhfn70GrfRJ3qUc9h1glFAckY',
    appId: '1:72071158816:web:2c9097070aa7b4046eb045',
    messagingSenderId: '72071158816',
    projectId: 'todo-app-428c2',
    authDomain: 'todo-app-428c2.firebaseapp.com',
    databaseURL: 'https://todo-app-428c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-428c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGCvgS_7fxR7BkuokLICXoDOdTWqwkAxs',
    appId: '1:72071158816:android:40b9803d453120da6eb045',
    messagingSenderId: '72071158816',
    projectId: 'todo-app-428c2',
    databaseURL: 'https://todo-app-428c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-428c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_YvoR0gizRMwlLV3C9MW0JO04CkF97Lc',
    appId: '1:72071158816:ios:ac013b8dce9bff256eb045',
    messagingSenderId: '72071158816',
    projectId: 'todo-app-428c2',
    databaseURL: 'https://todo-app-428c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-428c2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_YvoR0gizRMwlLV3C9MW0JO04CkF97Lc',
    appId: '1:72071158816:ios:ac013b8dce9bff256eb045',
    messagingSenderId: '72071158816',
    projectId: 'todo-app-428c2',
    databaseURL: 'https://todo-app-428c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-428c2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC41Cz0vJhfn70GrfRJ3qUc9h1glFAckY',
    appId: '1:72071158816:web:6a9008fa797e7e076eb045',
    messagingSenderId: '72071158816',
    projectId: 'todo-app-428c2',
    authDomain: 'todo-app-428c2.firebaseapp.com',
    databaseURL: 'https://todo-app-428c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-428c2.firebasestorage.app',
  );
}
